### ISSUE TITLE
Clear the open status of any repo window when app starts

### ISSUE THREAD

**Issue by ledleds** [rkclark/pullp#36]
When a repo is selected and the app is closed, upon reopening, the repo container is still open on the screen so it has to be closed to start. I think it would be cleaner if the state wasn't auto rehydrated on the Home page so this doesn't happen. 👍

**Comment by rkclark** [comment]
Yes the state controlling that currently open repo should not be persisted to local storage if possible... not sure whether the redux-persist package has that kind of granularity in its options or whether it will be necessary to implement something outside of it.
