### ISSUE TITLE
Being able to click the Pullp logo

### ISSUE THREAD

**Issue by bvjones** [rkclark/pullp#40]
With the pullp logo being in close proximity to the sync bar, it seems like they are connected.

I clicked on the logo expecting to trigger a manual sync but it isn't clickable.

**Comment by Jubblerbug** [comment]
I'll pick this issue up as my first open source contribution, if that's ok @rkclark ?

**Comment by rkclark** [comment]
Pullp logo is no longer shown in the app to clean up the ui
