### ISSUE TITLE
Show how long a PR has been open for

### ISSUE THREAD

**Issue by bvjones** [rkclark/pullp#53]
## Description of enhancement

When a pull request is been opened, show the time in hours since the PR has been created

## Rationale

It would help prioritise PRs that have been opened for a long amount of time and would prompt someone to review the PR.

**Comment by rkclark** [comment]
The app already shows the date the PR was opened so should be straight forward to add an `Open for xxx`. Would be good for this to show as minutes / hours / days depending on how long ago the PR was opened.

**Comment by sanjsanj** [comment]
@bvjones @rkclark This seems like a fun little task, would I be able to give it a go?  I'm thinking something like [moment.js](https://momentjs.com/)?

Haven't even looked at the code yet and I don't think this would be a trivial change for me to make but I fancy a go.

**Comment by rkclark** [comment]
@sanjsanj hey man, sure that would be great. I've not been picking these things up as I am working on a major re-write to replace Redux with Apollo Client. 

Would be good try to avoid moment if possible as it is pretty heavy. I believe lots of people are moving over to [date-fns](https://date-fns.org/) now as you can import just the modules you need from it. I've not tried it myself yet but I'd start there if I were you!

PS: some of the current code is a bit messy! Another reason for the re-write I am doing.

**Comment by sanjsanj** [comment]
I've just started having a look at the repo and because I'm running on Windows I'm getting some challenges.

So far I've been able to fix the line endings issues with the `dos2unix` command in git bash and removed the `BROWSER=none` from `npm start` to get it to load, but before I carry on looking at it is there any reason you know of why developing this on Windows wouldn't work?

**Comment by sanjsanj** [comment]
I opened #79 to deal with working in windows and will open a PR for this fix too for your feedback!

Unless I missed something this was super straight forward and seems to work fine.
