### ISSUE TITLE
Pullp 1.0.2 Linux AppImage Does Not Start 

### ISSUE THREAD

**Issue by N0taN3rd** [rkclark/pullp#68]
When using the Linux AppImage release (retrieved from the release page of this repo), the AppImage does not start due to an bootstrapping error (see image under **Current Behavior**). 
However, when building and running an **un-packed version** (built from src), the application runs as expected. 
Thanks for creating this app. Been wanting a tool for managing PRs and review requests for some time now. Keep up the good work!
## Your Version of Pullp
1.0.2

## Your OS
Ubuntu 16.04 LTS

## Expected Behavior
To launch normally (i.e when building and using unpacked version)

## Current Behavior
![pullpissue](https://user-images.githubusercontent.com/8648317/41608398-71550b4c-73b6-11e8-8c4b-3dc1b21813e0.png)

## Steps to Reproduce (for bugs)

1. Download [pullp-1.0.2-x86_64.AppImage](https://github.com/rkclark/pullp/releases/download/v1.0.2/pullp-1.0.2-x86_64.AppImage) or build packed version
2. Allow executing 
3. Run from command line (./pullp-1.0.2-x86_64.AppImage)
 
## Console Errors
None, see image under current behavior

**Comment by fmello-cit** [comment]
I had the exactly same error.

**Comment by rkclark** [comment]
@N0taN3rd Thanks for reporting the issue. I run the app myself on Ubuntu 16.04 without any problems, including v1.0.2. Have you tried double clicking it in the Files GUI rather than executing via the command line? (Would be strange if this made a difference but worth trying).

Let me know if this sorts it for you, otherwise I'll have to dig a bit deeper. Unfortunately I'm on holiday all of next week so bear with me if I am slow to reply.

**Comment by rkclark** [comment]
@N0taN3rd Hey man - thanks for reporting the issue! It seems there is a bug in the latest version of electron-builder. Am trying a downgrade...

**Comment by rkclark** [comment]
@N0taN3rd I've released a new version https://github.com/rkclark/pullp/releases/tag/1.0.4 Please give this a go! It works on my Ubuntu 16.04 machine. Cheers!

**Comment by fmello-cit** [comment]
Worked for me!

**Comment by N0taN3rd** [comment]
@rkclark the new version [tag/1.0.4](https://github.com/rkclark/pullp/releases/tag/1.0.4) works and closes this issue! 
Thank you for creating pullp!
Best
