### ISSUE TITLE
Issue running the dev environment on a Mac

### ISSUE THREAD

**Issue by Rayjk123** [rkclark/pullp#94]
## Your OS
Mac OS in built in terminal

## Issue
Currently following the README to do 
1. npm install
2. npm start

and I'm getting this error

TypeError: Cannot read property 'shell' of undefined
(anonymous function)
src/apollo/processNotifications.js:3
  1 | import reviewRequested from './notificationRules/reviewRequested';
  2 | 
> 3 | const { shell } = window.electron;
  4 | 
  5 | const triggerNotification = ({ notification: { title, message }, url }) => {
  6 |   /* eslint-disable no-new */

I was wondering if you had any insights into this issue?

**Comment by rkclark** [comment]
Seems like electron is not available (shell comes from electron as you can see on line 3 of the code snippet). I've just double check this all works for me on Mac with clean `npm install` followed by  `npm start` and it was fine. Try refreshing the app with `cmd+r` after the webpack dev server has reported itself working in the terminal i.e.

<img width="460" alt="Screenshot 2019-07-03 at 10 02 23" src="https://user-images.githubusercontent.com/15447744/60578760-ae286f80-9d79-11e9-9c28-76e836f35375.png">

Does that help?

**Comment by Rayjk123** [comment]
Yeah I just had to cmd+r
Thanks!

Currently trying to get this setup for github enterprise and got past the authentication portion, but then I run into a 404. Any ideas?

**Comment by rkclark** [comment]
Is Github Enterprise a self-contained version of Github hosted independently? If so... Pullp is set up to consume data only from the main Github API via the main Github oAuth system. In terms of the oAuth, this runs through a proxy service that I host myself, the code is here: https://github.com/rkclark/pullp-gatekeeper
