### ISSUE TITLE
Differentiate between Draft and Open PRs 

### ISSUE THREAD

**Issue by paullewisn** [rkclark/pullp#96]
## Description of enhancement

Currently, when on the `Monitor` screen, the number of Open PRs is presented in a purple circle. This number is made up of both `Open` and `Draft` PRs. 

As Draft PRs are not ready for review, it would be useful to display these separately. Perhaps in a smaller grey circle to the side, or maybe not at all? The `Reviewed by you` chart would also need adjusting to match.

## Rationale

This change would prevent the user from clicking through to GitHub expecting to find an Open PR, but instead finding a Draft.

## Your interest in contributing
I can work on this.

**Comment by rkclark** [comment]
Hi Paul,

Thanks for your suggestion and interest in contributing!

I've been thinking about this too for a while. Unfortunately I can't find anything in the Github API within the Pull Request schema that would allow us to know when a PR is in draft. You would have thought that they would have included it as a new pull request state but they don't appear to have done. https://developer.github.com/v4/explorer/

So step one might have to be to raise a Github API forum post to request this is added, unless you can find something I've missed.

Cheers

Rick

**Comment by ikigeg** [comment]
Just did a bit of nosing on this and found that the latest preview schema has [isDraft](https://developer.github.com/v4/previews/#draft-pull-requests-preview) which seems to be what is being requested. To make use of the preview stuff you need to supply a different header, which i've started on this branch https://github.com/rkclark/pullp/tree/is-draft-preview - fair bit to do to support it though. Plus you have to kinda keep your fingers crossed they don't change things 😄

**Comment by rkclark** [comment]
Thanks @ikigeg! Any clues as to when they might release the updated schema to prod?

**Comment by rkclark** [comment]
@paullewisn done in latest version 😄
