### ISSUE TITLE
Support for multiple github installations

### ISSUE THREAD

**Issue by DrGirlfriend** [rkclark/pullp#99]
## Description of enhancement
My team currently has repos in github.com as well as github enterprise. Is there a way to monitor both? 

The instructions were not clear on this scenario.

## Rationale
I could then keep track of PR's in both public github and enterprise github within one dashboard at the same time

## Your interest in contributing
Can't

**Comment by rkclark** [comment]
Hi, I'm afraid this isn't possible as the app is only capable of integrating with the public Github API. Sorry!
